### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by parasgarg123**

### CODE REVIEW

**Comment by arusahni** [comment]
@jcubic this person appears to be spamming repositories for Hacktoberfest. I received one such PR from them in my project. Could you label this PR as "spam" or "invalid"? [If enough folks do this, the Hacktoberfest organizers will disqualify them](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by jcubic** [comment]
@arusahni Marked all his PR with spam.

**Comment by jcubic** [comment]
@arusahni Just notice that there is a way to report the PR, I've also reported that PR as SPAM.

**Comment by arusahni** [comment]
@jcubic I've done that, too. Hopefully GitHub can take care of it.

**Pull request closed without merging**
